# Generated by Django 4.1.2 on 2024-06-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
