# Generated by Django 4.1.2 on 2024-06-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.FileField(default=1, upload_to='categoria/'),
            preserve_default=False,
        ),
    ]
