# Generated by Django 4.1.2 on 2024-06-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_rename_categoria_categoria_herramientas_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria_herramientas',
            new_name='Categoria_index',
        ),
    ]
