# Generated by Django 4.1.2 on 2024-06-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_rename_categoria_herramientas_categoria_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_index',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
