# Generated by Django 4.1.2 on 2024-06-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_categoria_index_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_index',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
