# Generated by Django 4.1.2 on 2024-06-29 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_remove_categoria_id_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategorias',
            name='categoria',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='tienda.categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
