# Generated by Django 4.1.2 on 2024-06-29 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_categoria_id_subcategorias_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorias',
            name='descripcion',
        ),
    ]
