# Generated by Django 4.1.2 on 2024-06-29 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_remove_subcategorias_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorias',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria'),
        ),
    ]
