# Generated by Django 4.1.2 on 2024-06-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0020_alter_categoria_id_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='imagen',
            field=models.FileField(default=1, upload_to='subcategoria/'),
            preserve_default=False,
        ),
    ]
