# Generated by Django 4.1.2 on 2024-06-29 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0021_subcategoria_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('valor', models.IntegerField(max_length=10)),
                ('imagen', models.FileField(upload_to='producto/')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.subcategoria')),
            ],
        ),
    ]
